name: CI/CD Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # -------- BUILD CLIENT --------
    - name: Build Client
      run: |
        cd client
        npm ci
        npm run build

    # -------- BUILD ADMIN --------
    - name: Build Admin
      run: |
        cd admin
        npm ci
        npm run build

    # -------- UPLOAD CLIENT --------
    - name: Upload Client Build
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "client/dist/*"
        target: "/var/www/enabazar-server/client"

    # -------- UPLOAD ADMIN --------
    - name: Upload Admin Build
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "admin/dist/*"
        target: "/var/www/enabazar-server/admin"

    # -------- BACKEND DEPLOY --------
    - name: Deploy Backend
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/enabazar-server/server
          git reset --hard
          git pull origin main
          npm ci
          pm2 restart project-backend
          sudo systemctl reload nginx
